version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:12
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  redis:
      image: "redis:latest"
      container_name: "redis-container"
      ports:
        - "6379:6379"

  payments:
    build: ./payments
    container_name: payments
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq

  inventory:
    build: ./inventory
    container_name: inventory
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - payments

  order:
    build: ./order
    container_name: order
    ports:
      - "8003:8003"
    depends_on:
      - kafka

  order_processing:
    build: ./order_processing
    container_name: order_processing
    ports:
      - "8004:8004"
    depends_on:
      - kafka
      - redis

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-container
    environment:
      - CLICKHOUSE_DB=mydatabase
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=your_secure_password
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  order_stats:
    build: ./order_stats
    container_name: order_stats
    ports:
      - "8005:8005"

volumes:
  clickhouse_data:
  postgres_data:
